# Generated by Django 2.2 on 2020-03-20 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnm', models.CharField(max_length=50)),
                ('lastnm', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('pswd', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('birthdate', models.DateTimeField()),
                ('bio', models.TextField(null=True)),
                ('profilePic', models.TextField(null=True)),
                ('isAdopted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fosteredby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='appCatAdoption.User')),
                ('traits', models.ManyToManyField(related_name='cats', to='appCatAdoption.Trait')),
            ],
        ),
    ]
